// flow-typed signature: d09f238dadff5c746205cab26be290ec
// flow-typed version: <<STUB>>/kakaojs_v1.2.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kakaojs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kakaojs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kakaojs/kakao' {
  declare module.exports: any;
}

declare module 'kakaojs/kakao.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kakaojs/kakao.js' {
  declare module.exports: $Exports<'kakaojs/kakao'>;
}
declare module 'kakaojs/kakao.min.js' {
  declare module.exports: $Exports<'kakaojs/kakao.min'>;
}
