// flow-typed signature: c8cc1b06d480e394e2af371b264d535e
// flow-typed version: <<STUB>>/laravel-echo_v1.8.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'laravel-echo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'laravel-echo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'laravel-echo/dist/echo.common' {
  declare module.exports: any;
}

declare module 'laravel-echo/dist/echo.iife' {
  declare module.exports: any;
}

declare module 'laravel-echo/dist/echo' {
  declare module.exports: any;
}

declare module 'laravel-echo/jest.config' {
  declare module.exports: any;
}

declare module 'laravel-echo/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'laravel-echo/dist/echo.common.js' {
  declare module.exports: $Exports<'laravel-echo/dist/echo.common'>;
}
declare module 'laravel-echo/dist/echo.iife.js' {
  declare module.exports: $Exports<'laravel-echo/dist/echo.iife'>;
}
declare module 'laravel-echo/dist/echo.js' {
  declare module.exports: $Exports<'laravel-echo/dist/echo'>;
}
declare module 'laravel-echo/jest.config.js' {
  declare module.exports: $Exports<'laravel-echo/jest.config'>;
}
declare module 'laravel-echo/rollup.config.js' {
  declare module.exports: $Exports<'laravel-echo/rollup.config'>;
}
