// flow-typed signature: 7ac465bf188d33b218e56dc073c5f7d1
// flow-typed version: <<STUB>>/react-rating-stars-component_v2.2.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rating-stars-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rating-stars-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rating-stars-component/dist/hooks/useConfig' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/dist/react-stars' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/dist/star' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/example/bundle' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/example' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/src/hooks/useConfig' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/src/react-stars' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/src/star' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/webpack.config' {
  declare module.exports: any;
}

declare module 'react-rating-stars-component/webpack.production.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rating-stars-component/dist/hooks/useConfig.js' {
  declare module.exports: $Exports<
    'react-rating-stars-component/dist/hooks/useConfig'
  >;
}
declare module 'react-rating-stars-component/dist/react-stars.js' {
  declare module.exports: $Exports<
    'react-rating-stars-component/dist/react-stars'
  >;
}
declare module 'react-rating-stars-component/dist/star.js' {
  declare module.exports: $Exports<'react-rating-stars-component/dist/star'>;
}
declare module 'react-rating-stars-component/example/bundle.js' {
  declare module.exports: $Exports<
    'react-rating-stars-component/example/bundle'
  >;
}
declare module 'react-rating-stars-component/example/index' {
  declare module.exports: $Exports<'react-rating-stars-component/example'>;
}
declare module 'react-rating-stars-component/example/index.js' {
  declare module.exports: $Exports<'react-rating-stars-component/example'>;
}
declare module 'react-rating-stars-component/src/hooks/useConfig.js' {
  declare module.exports: $Exports<
    'react-rating-stars-component/src/hooks/useConfig'
  >;
}
declare module 'react-rating-stars-component/src/react-stars.js' {
  declare module.exports: $Exports<
    'react-rating-stars-component/src/react-stars'
  >;
}
declare module 'react-rating-stars-component/src/star.js' {
  declare module.exports: $Exports<'react-rating-stars-component/src/star'>;
}
declare module 'react-rating-stars-component/webpack.config.js' {
  declare module.exports: $Exports<
    'react-rating-stars-component/webpack.config'
  >;
}
declare module 'react-rating-stars-component/webpack.production.config.js' {
  declare module.exports: $Exports<
    'react-rating-stars-component/webpack.production.config'
  >;
}
