// flow-typed signature: b6a9c3b16f7ec7dc7235256992c74300
// flow-typed version: <<STUB>>/react-toastify_v6.0.9/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toastify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toastify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toastify/dist' {
  declare module.exports: any;
}

declare module 'react-toastify/dist/react-toastify.cjs.development' {
  declare module.exports: any;
}

declare module 'react-toastify/dist/react-toastify.cjs.production.min' {
  declare module.exports: any;
}

declare module 'react-toastify/dist/react-toastify.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toastify/dist/index' {
  declare module.exports: $Exports<'react-toastify/dist'>;
}
declare module 'react-toastify/dist/index.js' {
  declare module.exports: $Exports<'react-toastify/dist'>;
}
declare module 'react-toastify/dist/react-toastify.cjs.development.js' {
  declare module.exports: $Exports<
    'react-toastify/dist/react-toastify.cjs.development'
  >;
}
declare module 'react-toastify/dist/react-toastify.cjs.production.min.js' {
  declare module.exports: $Exports<
    'react-toastify/dist/react-toastify.cjs.production.min'
  >;
}
declare module 'react-toastify/dist/react-toastify.esm.js' {
  declare module.exports: $Exports<'react-toastify/dist/react-toastify.esm'>;
}
