// flow-typed signature: 0f51caf475968ea57b79bff0549d5a70
// flow-typed version: <<STUB>>/react-naver-login_v0.1.4/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-naver-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-naver-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'react-naver-login/index' {
  declare module.exports: $Exports<'react-naver-login'>;
}
declare module 'react-naver-login/index.js' {
  declare module.exports: $Exports<'react-naver-login'>;
}
