/* eslint-disable camelcase */
// import libs
import { create } from 'apisauce';

const API_URI = process.env.REACT_APP_API_URL;

export const ROUTES = {
  AGE_CATEGORY: 'setting/ageCategory',
  SUBJECT_CATEGORY: 'setting/subjectCategory',
  SETTING_USER: 'setting/user',
  USER_ACCESS: 'user/access',
  GET_DATA_BEST_FRIEND: (id) => `age/${id}`,
  API_SEARCH_CONDITION: `search/condition`,
  API_GET_LIST_CONSULTATION: `consultation/history`,
  API_GET_DETAIL_CONSULTATION: (qnaId) => `consultation/content/${qnaId}`,
  API_SEARCH_FILTER: (key) => `search/filter?keyword=${key}`,
  API_SEARCH_DETAIL: (keyword) => `search/filter/detail?keyword=${keyword}`,
  GET_DATA_AUDIO_BOOK_DETAIL: (id) => `audiobook/${id}`,
  GET_AUDIO_BOOK_SERIES: (groupId, mediaTypeId) =>
    `audiobook/${groupId}/${mediaTypeId}`,
  CONSULTATION_SAVE: 'consultation/save',
  GET_DATA_MAIN: 'home',
  API_SEARCH_CATEGORY: `search/category`,
  API_THEME_DJ: (id) => `theme/dj/${id}`,
  API_THEME_MONTH_DETAIL: (id) => `theme/month/${id}`,
  API_THEME_MONTH: `theme/month`,
  API_THEME_CHARACTER_DETAIL: (id) => `theme/character/${id}`,
  API_THEME_SCHOOL: (id) => `theme/school/${id}`,
  API_THEME_LIKE_THIS: (id) => `theme/likethis/${id}`,
  API_ANNOUNCEMENT_HISTORY: `announcement/history`,
  API_ANNOUNCEMENT_DETAIL: (id) => `announcement/content/${id}`,
  API_USER_MY: `user/my`,
  DELETE_CONSULTATION_API: `consultation/delete`,
  API_SETTING_USER_CATEGORY: 'setting/user/category',
  API_SETTING_CONTENT: 'user/setting/content',
  API_SEARCH_KEY_DETAIL: 'search/filter/keyword/detail',
  API_USER_STATUS_PLAY: 'user/status/play',
  API_LIKE_PLAYER: (id) => `user/like/${id}`,
  API_SAVE_FILE: (id) => `consultation/save/file/${id}`,
  API_GET_INFORMATION_USER: `user/information`,
  API_UPDATE_AVATAR: (id) => `user/icon/?iconId=${id}`,
  API_SECURE_CONTENT: `playbook/secure/content`,
  API_CHECK_PLAY: `playbook/play/check`,
  API_SAVE_HISTORY_BANNER: (id) => `banner/history/${id}`,
  // 2ST
  API_SIGN_UP: `user/join`,
  API_CHECK_EMAIL: `user/email`,
  API_SIGN_IN: `user/login`,
  API_GET_LIBRARY: `library`,
  API_GET_LIBRARY_DETAIL: (groupId) => `library/${groupId}`,
  API_GET_LIST_REVIEW: (id) => `audiobook/review/${id}`,
  API_SAVE_REVIEW: `audiobook/review/save`,
  API_CATEGORY_REPORT: `report/category`,
  API_SAVE_REPORT: `report`,
  API_GET_LIST_SUBJECT: `studio/subject`,
  API_GET_LIST_PLAY_STUDIO: (id) => `studio/play/group/${id}`,
  API_GET_LIST_PLAY_STUDIO_DETAIL: (id) =>
    `studio/play/group/product?groupId=${id}`,
  API_GET_LIST_RECORD: `studio/record`,
  API_GET_LIST_STUDIO_MONTH: `studio/month`,
  API_GET_LIST_STUDIO_CHALLENGE: `studio/challenge`,
  API_GET_LIST_RECORD_USER: `studio/record/user`,
  API_UPDATE_RECORD: (data) =>
    `studio/record/update/${data.id}/${data.title}/${data.nickName}/${data.usable}`,
  API_DELETE_RECORD: (id) => `studio/record/delete/${id}`,
  API_SIGN_IN_FACEBOOK: `user/facebook/join`,
  API_SIGN_IN_KAKAO: `user/kakao/join`,
  API_SIGN_IN_NAVER: `user/naver/join`,
  API_STUDIO_PLAYER: (groupId) => `studio/play/like/${groupId}`,
  API_GET_DETAIL_PLAY_STUDIO: (id) => `studio/detail/${id}`,
  API_GET_LIST_REVIEW_STUDIO: (id) => `studio/review/${id}`,
  API_SAVE_REVIEW_STUDIO: `studio/review/save`,
  API_DELETE_REVIEW_STUDIO: (id) => `studio/review/delete/${id}`,
  API_DELETE_REVIEW: (reviewId) => `audiobook/review/delete/${reviewId}`,
  API_GET_LIST_PLAYLIST: `studio/play/group/my/web`,
  API_PUSH_SETTING: `user/information/push/setting`,
  API_GET_LIST_FILTER_STUDIO: `studio/contents/filter`,
  API_UPDATE_PASSWORD: `user/password/update`,
  API_UPDATE_PHONE: `user/information/setting`,
  API_GET_DETAIL_STUDIO_STUDIO: `studio/contents/detail/`,
  API_SETTING_WI_FI: `user/information/play/setting`,
  API_GET_LIST_SERIES_STUDIO: (id) => `studio/series/${id}`,
  API_LIKE_STUDIO: (id) => `studio/like/${id}`,
  API_SAVE_PLAY_GROUP: `play/group/save`,
  API_FIND_PASSWORD: `user/send/password`,
  API_PAYMENT_VALIDATE: `payment/validate`,
  API_REGISTER_COUPON: `coupon/register`,
  API_DELETE_GROUP_STUDIO: (id) => `studio/play/group/delete/${id}`,
  API_GET_DATA_THEME_BANNER: (id) => `custom/theme/banner/detail/${id}`,
  API_GET_DATA_THEME_DEFAULT: (id) => `custom/theme/default/detail/${id}`,
  GET_DATA_SLIDE_TODAY: `theme/today`,
  API_CHECK_AUDIO_PLAYER_VALID: `audiobook/player/valid`,
  API_USER_STATUS_PLAY_STUDIO: 'user/studio/status/play',
  API_SIGN_IN_APPLE: 'user/apple/join',
  API_CHECK_USER_SNS_LOGIN: `user/sns/check`,
  API_REGISTER_HISTORY_PAGE: (entryCode) =>
    `user/page/entry/history?entryCode=${entryCode}`,
  API_SAVE_HISTORY_SEARCH: `user/search/entry/history`,
  API_SAVE_HISTORY_SEARCH_DETAIL: `user/search/history`,
};

export const API = create({
  baseURL: API_URI,
});
