// flow-typed signature: 1ab6dfdfdd96dbff9d0052e3cc0c7df0
// flow-typed version: <<STUB>>/swiper/react_v6.3.5/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swiper/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swiper/react' {
  declare module.exports: any;
}
