// flow-typed signature: 37a601713a1265ea151dde34f8f6e264
// flow-typed version: <<STUB>>/@dohyeon/react-naver-login_v0.1.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dohyeon/react-naver-login'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dohyeon/react-naver-login' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dohyeon/react-naver-login/dist/index.es' {
  declare module.exports: any;
}

declare module '@dohyeon/react-naver-login/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dohyeon/react-naver-login/dist/index.es.js' {
  declare module.exports: $Exports<'@dohyeon/react-naver-login/dist/index.es'>;
}
declare module '@dohyeon/react-naver-login/dist/index' {
  declare module.exports: $Exports<'@dohyeon/react-naver-login/dist'>;
}
declare module '@dohyeon/react-naver-login/dist/index.js' {
  declare module.exports: $Exports<'@dohyeon/react-naver-login/dist'>;
}
